---
- name: Implementing tags
  hosts: all
  vars:
    a: tree
    b: present
    c: yes
  tasks:
    - name: Install tree
      apt:
        name: "{{a}}"
        state: "{{b}}"
        update_cache: "{{c}}"
      tags: 
        - tree_installation
        - always
    - name: Create user
      user:
        name: anu
        password: intelliqit
      tags: user_creation
    - name: Copy passwd file
      copy:
        src: /etc/passwd
        dest: /tmp
...
