---
- name: Install  tree based on OS version
  hosts: all
  tasks:
    - name: Install git on ubuntu using apt
      apt:
        name: tree
        state: present
        update_cache: yes
      when: ansible_distribution == "Ubuntu"
    - name: Install git on redhat using yum
      yum:
        name: tree
        state: present
        update_cache: yes
      when: ansible_distribution == "RedHat"
...
