---
- name: User creation using host scope variables
  hosts: 172.31.23.91
  tasks:
    - name: Create user
      user:
        name: "{{a}}"
        password: "{{b}}"
        uid: "{{c}}"
        home: "{{d}}"
        shell: "{{e}}"
        comment: "{{f}}"
...

