---
- name: Create user on all the servers
  hosts: all
  tasks:
    - name: User creation
      user:
        name: Ravi
        password: intelliqit
        uid: 6789
        home: /tmp/Ravi
        comment: "A normal user"
...
