---
- name: Install various s/w app's
  hosts: all
  tasks:
    - name: Install multiple s/w's
      apt:
        name: "{{item}}"
        state: present
        update_cache: yes
      with_items:
        - openjdk-17-jdk
        - maven
        - git
...
